#!/usr/bin/env bash
SEP=":"
case "`uname`" in
  CYGWIN*) SEP=";";;
esac

# Use relative path for cygwin...
absolute=`readlink -f $(dirname $0)/..`
current=`readlink -f .`
# http://stackoverflow.com/questions/2564634/bash-convert-absolute-path-into-relative-path-given-a-current-directory
H2O=./$(perl -MFile::Spec -e 'print File::Spec->abs2rel("'"$absolute"'","'"$current"'")')

#-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=y
java -ea -cp $H2O/target/h2o.jar water.sys.EC2 $@

