#!/usr/bin/env bash
SEP=":"
case "`uname`" in
  CYGWIN*) SEP=";";;
esac
#-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=y
java -ea -cp ../target/h2o.jar$SEP../py/jython.jar org.python.util.jython $@