#!/usr/bin/env bash
SEP=":"
H2O=$(dirname $0)/..
case "`uname`" in
  CYGWIN*) SEP=";";H2O=$(cygpath -w $H2O);;
esac

#-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=y
PP=$H2O/py$SEP$H2O/py/Lib
CP=$H2O/target/h2o.jar$SEP$H2O/py/jython.jar
java -ea -Dpython.path=$PP -cp $CP water.Boot -mainClass org.python.util.jython $@
